language: python
python:
- '2.7'
env:
  global:
  - DJANGO_SETTINGS_MODULE='settings.testing'
install:
- pip install -q -r requirements/testing.txt
- pip install -q python-coveralls
- pip install -q coverage
- npm install bower
script:
- python photo_editor/manage.py bower install -- -s
- python photo_editor/manage.py collectstatic --noinput
- python photo_editor/manage.py makemigrations
- python photo_editor/manage.py migrate
- coverage run --source photo_editor/app photo_editor/manage.py test
after_success:
- coveralls
before_deploy: git fetch --unshallow
deploy:
  provider: heroku
  api_key:
    secure: kmtxZ9DleOMWvz5iXDxhzP+W1hY8DQvbJAb3kneEJzzillRt1WLg4Sx88Wl+JgGntamAiKegiYPjjYkIlojqj5ScOwd5jM0DmaRaZJsVFUV26SBpe5RLR4K5xZtwGUsCxk42o48XRwVqCAfw48gy+sZTNLcYX7QTvmueyJfB9n4HfzEdemXRd/lZnKHhTKvsjPG1qr0DesWPIi5IETt330ImpEkD08fnPfSX1d0CdpC6xCqEt3D7drheRpLa5k6KU2Yc/nphPjDNaMxr7K5e2E7EAi/IZ99hOWyjufJti/P2tpBT7wkPea9210+5IFmTuOgobBIJs8B9riAFZjLIBAWR0+WZiOzo4HoKq/TFk+TjcQIkADoi5nHoLsnOnl44VHtbaFP8ZXL+bk3amnNIZ15l23697GRO65waEf4plj0TfKDbuCsPM2ycmindBJMmx9uajL0BkR3DlrK7x5t2KpZ8ClthRPfR0jqcI2kTxch/VTXrpf23ii1FIeyO+4K1QYKIBZkN7Cq8P0GG/O4RkM10yxgiyE4aciomZTCa3A0lefpR1Q5kyL4Tg8P+IgYKq7PcwVha9LSX+BylopMx1BqUbfe44O50QKvEfs64cy0d4xg/DY3XYJmTNM0uffSWfpc8c0IIdLfPRU4NzSnQH9R1sPfsSHfpqYv0hS8MneI=
  skip_cleanup: true
  strategy: git
  app:
    develop: photo-editr
  run:
  - export DJANGO_SETTINGS_MODULE=settings.staging
  - python photo_editor/manage.py collectstatic --noinput
  - python photo_editor/manage.py makemigrations
  - python photo_editor/manage.py migrate auth
  - python photo_editor/manage.py migrate
  - python photo_editor/manage.py syncdb --noinput
after_deploy:
- heroku ps:scale web=1 --app photo-editr
